image: ilaborie/hugonode

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - hugo version
  - echo node `node --version`
  - echo yarn `yarn --version`
  - yarn

sandbox:
  script:
    - hugo -F
    - node tools/pdf.js
    - node tools/minify.js
    - firebase use default
    - firebase deploy --token "$FIREBASE_SANDBOX_TOKEN"
  artifacts:
    paths:
      - public
  only:
    - develop

prod:
  variables:
    HUGO_ENV: production
  script:
    - hugo --baseURL https://2019.devfesttoulouse.fr/
    - node tools/pdf.js
    - node tools/minify.js
    - firebase use prod
    - firebase deploy --token "$FIREBASE_PROD_TOKEN"
  artifacts:
    paths:
      - public
  only:
    - master
