baseURL = "https://aeroki.ru/"
languageCode = "ru"
defaultContentLanguage = "ru" 
title = "Точка.Pro Центр иновационного творчества"
# Theme
theme = "devfest-theme-hugo"

# Params
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-37717223-8"

[params]
    title = "Точка.Pro Кисловодск"
    date = "2020-10-03"
    description = "Центр молодежного творчества в Кисловоске - создаем гениев из талантливых людей"
    images = ["/images/social-share.jpg"]
    email = "sha.egor@gmail.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "We :heart:️ chocolatines"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "https://t.me/+BBRnBhaUSv80NzZi"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

[menu]
[[menu.main]]
    identifier = "rfrk"
    name = "РФРК"
    url = "https://rfrk.ru/"
    weight = 200
    external = true

[languages]
[languages.ru]
    weight = 1
    languageName = "ru"

[languages.ru.params]
    description = "Центр инновационного творчества"

[languages.en]
    weight = 2
    languageName = "gb"

[languages.fr]
    weight = 3
    languageName = "fr"

[languages.fr.params]
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
